In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
# 2-D array 
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# creating numpy array, works 'like' python range()
# arange(start, stop, step)

np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
# zeros 5 - rows, 2 - cols
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
# returns 10 evenly spaced points from 0 - 5
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.linspace(0, 100, 50)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [18]:
# identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.random.rand(5)

array([0.87534829, 0.41306212, 0.5447436 , 0.61198112, 0.69235424])

In [21]:
np.random.rand(5,2)

array([[0.31981796, 0.43504959],
       [0.65582712, 0.85850145],
       [0.70990193, 0.60321504],
       [0.6374941 , 0.78357522],
       [0.43618262, 0.84803445]])

In [27]:
# normal dist centered around 0
np.random.randn(5,2)

array([[-1.39505753,  0.72473111],
       [-0.87482279,  0.14699008],
       [ 0.53265349,  0.88871717],
       [-0.03825209, -1.15075089],
       [-0.62666933, -1.47727872]])

In [33]:
# random integers from low to high (exclusive)
np.random.randint(1,100, 10)

array([57, 99, 91, 81, 66, 36, 28,  7, 45, 49])

In [34]:
arr = np.arange(25)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
# notes: #rows x #col == #elements in arr
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
arr.max()

24

In [40]:
# index of min value
arr.min()

0

In [44]:
# index of max value
arr.argmax()

24

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
# numpy doesn't implicitly make copy of array
# must be set explicitly
# Note: array aliasing

arr_copy = arr.copy()

In [50]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
arr_copy[:2] = 5

In [52]:
arr_copy

array([ 5,  5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
# Indexing and Selection

In [55]:
arr_2d = np.array([[5,10,15], [20,25,30],[35,40,45]])

In [56]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [57]:
# double bracket notation:
arr_2d[0][0]

5

In [58]:
# single bracket notation:
arr_2d[1,2]
# does it only work with numpy arrays?

30

In [59]:
# conditional selection
arr = np.arange(1,11)

In [64]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [65]:
# return arr elements where bool_arr = true
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [71]:
# exercise
new = np.arange(50).reshape(5,10)
new

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [75]:
even = new[new%2==0]
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [74]:
odd = new[new%2 == 1]
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [ ]:
# NumPy Operations
